server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/garderie_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: user
      password: pass
      roles: USER

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

application:
  jwt:
    expiresAt: 846000
    headerPrefix: "Bearer "
    secret: "Y2nr@Svs1#Rume@v9^r$$hwTm563QpxLfdDTO$VdLLMnNRJmcQ"
    headerKey: "Authorization"

custom:
  property: "ma prop custom"
  other: "thing"
  number: 3
  list:
    - 1
    - 2
    - 3